let a = parseInt(prompt("Enter a number"));
let b = parseInt(prompt("Enter a number"));
const add = a + b;
const subtract = a - b;
const multiplly = a * b;
const devide = a / b;
const modulo = a % b;
console.log("Add:", add);
console.log("subtract:", subtract);
console.log("modulo:", modulo);
console.log("multiplly:", multiplly);
console.log("devide:", devide);
